language: node_js
node_js:
  - '10'
  - '12'
cache: npm
script:
  - npm run coverage:ci
jobs:
  include:
    - stage: master-coverage
      if: (branch = master)
      git:
        depth: 1
      node_js: '12'
      deploy:
        - provider: script
          script: |
                  npm install --save-dev coveralls@2
                  nyc report --reporter=text-lcov | coveralls
    - stage: release
      if: (tag =~ ^v)
      git:
        depth: 1
      node_js: '12'
      deploy:
        - provider: npm
          edge: true
          registry: https://registry.npmjs.org
          access: public
          on:
            tags: true
            repo: jormaechea/aws-http-api-gateway
      after_deploy:
        - |
          npm install --save-dev coveralls@2
          nyc report --reporter=text-lcov | coveralls
